name: "Unit tests"

on:
  pull_request:
    branches: [taiko]
  push:
    branches: [taiko]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          repository: taikochain/taiko-geth

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18

      - name: Lint
        run: make lint

      - name: Test
        env:
          ANDROID_HOME: ""
          TAIKO_TEST: true
        run: make test
